version: '3'

services:
  admin_api:
    build:
      context: .
      dockerfile: admin_api/Dockerfile
    container_name: admin_api
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq

  frontend_api:
    build:
      context: .
      dockerfile: frontend_api/Dockerfile
    container_name: frontend_api
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer_admin:
    build:
      context: .
      dockerfile: admin_api/Dockerfile
    container_name: consumer_admin
    working_dir: /app/admin_api
    volumes:
      - ./admin_api:/app/admin_api
    command: python consumers.py
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - admin_api
      - rabbitmq

  consumer_frontend:
    build:
      context: .
      dockerfile: frontend_api/Dockerfile
    container_name: consumer_frontend
    working_dir: /app/frontend_api
    volumes:
      - ./frontend_api:/app/frontend_api
    command: python consumers.py
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - frontend_api
      - rabbitmq
